### ISSUE TITLE
TypeScript declaration file is not included into the published npm package

### ISSUE THREAD

**Issue by vldmrkl** [psalaets/line-intersect#1]
I see that you have a [TypeScript declaration file](https://github.com/psalaets/line-intersect/blob/master/index.d.ts) in your repo, but it isn't included into the package published on npm. Thus, users have to copy and paste this file into the project folder in order for TypeScript to compile without errors.

It would be really nice if npm package had these type definitions by default.

**Comment by psalaets** [comment]
Thanks for reporting this. I just published version 2.2.2 which should include the typescript defs.

**Comment by vldmrkl** [comment]
Thank you, @psalaets!
